#FIND_PACKAGE(Minizip)

FIND_PATH(MINIZIP_INCLUDE_DIR_zh NAMES zip.h PATHS /include/minizip /usr/include/minizip /usr/local/include/minizip /opt/local/include/minizip)
FIND_LIBRARY(MINIZIP_LIBRARY NAMES minizip)

IF (MINIZIP_INCLUDE_DIR_zh AND MINIZIP_LIBRARY)
  SET(MINIZIP_INCLUDE_DIRS "${MINIZUO_INCLUDE_DIR_zh};${MINIZIP_INCLUDE_DIRS}")
  SET(MINIZIP_LIBRARIES ${MINIZIP_LIBRARY})
  SET(MINIZIP_FOUND true)
ENDIF()
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(Minizip DEFAULT_MSG MINIZIP_LIBRARIES MINIZIP_INCLUDE_DIRS)
